### ISSUE TITLE
Logstash can't get data from multi redis 

### ISSUE THREAD

**Issue by vankhoa011** [logstash-plugins/logstash-input-redis#12]
I configured Logstash Input which get data from two redis. However, Logstash only get data from one redis. I don't know it is a bug whether or not ?

My logstash version is 1.5.0. Thanks

```
input {
  redis {
    host => "10.0.0.50"
    type => "logs"
    data_type => "list"
    key => "LOG"
    codec => "json"
  }
  redis {
    host => "10.0.3.202"
    type => "logs"
    data_type => "list"
    key => "LOG"
    codec => "json"
  }
}

filter {
  date {
    match => [ "timestamp", "UNIX_MS" ]
  }
}
```

**Comment by blysik** [comment]
{:timestamp=>"2015-06-16T16:26:38.160000-0700", :message=>"Redis connection problem", :exception=>#<Redis::CommandError: ERR max number of clients reached>, :level=>:warn}

Do you have an error like that with your config?  Is this because of the default threads being 1?

**Comment by blysik** [comment]
Nevermind.  My problem was related to the redis servers not having any free connections.

**Comment by guyboertje** [comment]
@blysik - does this mean that you **do** have two different redis inputs pointing at different redis servers and that it all works just fine?

**Comment by guyboertje** [comment]
Seems resolved . Closing
