### ISSUE TITLE
v1.0.1 "Couldn't find any input plugin named 'redis'"

### ISSUE THREAD

**Issue by nxhack** [logstash-plugins/logstash-input-redis#15]
logstash 1.5.3. When version up input-redis from 1.0.0 to 1.0.1, error occured.

{:timestamp=>"2015-07-27T09:03:31.372000+0900", :message=>"The error reported is: \n  Couldn't find any input plugin named 'redis'. Are you sure this is correct? Trying to load the redis input plugin resulted in this error: NameError"}

Maybe the cause is...

+module Logstash module Inputs class Redis < LogStash::Inputs::Threadable
+# class LogStash::Inputs::Redis < LogStash::Inputs::Threadable

**Comment by nxhack** [comment]
module Logstash module Inputs class Redis < LogStash::Inputs::Threadable
                  ^
module LogStash

work fine.

**Comment by shaharmor** [comment]
+100!

**Comment by suyograo** [comment]
@nxhack thanks for this
@guyboertje how come our tests didn't catch this?

**Comment by suyograo** [comment]
@nxhack does this work, did you test it?

**Comment by nxhack** [comment]
@suyograo yes. it work fine in my logstash configs.

**Comment by suyograo** [comment]
@nxhack ok, just tested this on 1.0.1. Its broken :-1: . #17 fixes it, will merge it in.

**Comment by suyograo** [comment]
@nxhack @shaharmor Thanks for the spot. 1.0.2 has been published which fixes this.

**Comment by suyograo** [comment]
Fixed via https://github.com/logstash-plugins/logstash-input-redis/pull/17

**Comment by guyboertje** [comment]
Humble apologies.  The specs used the typo.  I will fix the specs as well.
