### ISSUE TITLE
Any plans to support "lpop" command with polling?

### ISSUE THREAD

**Issue by MichaelScofield** [logstash-plugins/logstash-input-redis#23]
For some reasons(we reimplemented Redis with minimum commands supported), we cannot use the "blpop" nor the subscribe. Only the "lpop" is allowed.

So I'm wondering if there are any plans to support the lpop. If not, can I submit some PR?

Thx! :-)

**Comment by jordansissel** [comment]
I'm not sure I totally understand your use case - you have a custom system that provides a partial implementation of the Redis command set? If so, why not implement BLPOP on your side as this "lpop with polling" design?

Alternately, you could maintain a fork of this plugin that uses your own reading strategy (lpop + sleep, etc)

**Comment by MichaelScofield** [comment]
The blpop support in our custom Redis is out of my control. Anyway, I will maintain a fork to implement my requirements.

Thanks for the reply!
