### ISSUE TITLE
Improve the batch_count behaviour

### ISSUE THREAD

**Issue by guyboertje** [logstash-plugins/logstash-input-redis#25]
Experiment with batching to fetch enough to fill the queue, anymore would be a waste.

**Comment by suyograo** [comment]
Can we increase the `batch_size` to 100 by default. From a recent user debugging, I saw a big jump in throughput and reduction in CPU utilization when changed from `1` to `500`

**Comment by guyboertje** [comment]
I am sure we can and also improve the LUA script. See [this comment](https://github.com/logstash-plugins/logstash-input-redis/issues/8#issuecomment-192244583)

**Comment by blavoie** [comment]
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html
documentation not updated
