### ISSUE TITLE
Add pattern_channel channel name matching

### ISSUE THREAD

**Issue by riguy724** [logstash-plugins/logstash-input-redis#32]
I'd really like to see if we can incorporate the channel name for the redis pattern_channel data type.  It looks like right now the channel is just being thrown away in the response when receiving messages under the pattern channel listener.  This would be pretty easy to do if we can just add the name of the channel to the queue event propogated [here](https://github.com/logstash-plugins/logstash-input-redis/blob/master/lib/logstash/inputs/redis.rb#L332).

Any thoughts on this?  I know redis is widely used broker for logstash messages, so i'm not sure what type of performance impact this would have, but it would make generic channel subscriptions and then attaching particular channel names in the forwarded output much simpler.

**Comment by jordansissel** [comment]
We could probably include the channel in the event metadata, and if folks want that included as a part of the event itself , that would be possible then in their Logstash config.

Thoughts? It should be a pretty easy patch.

**Comment by riguy724** [comment]
Yeah, that sounds awesome to me. I'm new to Logstash and have never programmed in ruby before, but from what I can make out looking through the source it seems like it would be fairly straightforward.  If it's possible to add that it'd be greatly appreciated!

**Comment by jordansissel** [comment]
@riguy724 yeah I think we can add it. I'll see if we can do that this soon. <3

**Comment by joac** [comment]
I added a pull request that solves this https://github.com/logstash-plugins/logstash-input-redis/pull/46

**Comment by riguy724** [comment]
Awesome!  Thanks!
