### ISSUE TITLE
logstash-input-redis: accept an array for the host setting

### ISSUE THREAD

**Issue by maximgue** [logstash-plugins/logstash-input-redis#38]
While the _logstash-output-redis_ plugin's *host* setting accepts an array of hosts, this is currently not the case of _logstash-input-redis_.

Having the possibility to define an array of Redis hosts from which to read data would be particularly interesting in the case of a master-slave Redis setup (for load-balancing and/or fail-over).

**Comment by purbon** [comment]
related to #24

**Comment by guyboertje** [comment]
It is one thing to make the config an array and quite another to implement load balancing or fail over.
Usually when one uses multiple redis inputs to connect to different redis endpoints.

**Comment by purbon** [comment]
yeah, @guyboertje point is a very valid one. I guess here the situation would be to make the at less the input behave a bit closer to the output, things like:

```
input {
	redis {
		host => "127.0.0.1:6379"
		key => "logstash"
		data_type => "list"
	}
}
```

will work for the output, but not for the input.  Without implementing file over, and more going to what #24 proposes, I guess having this is good. What do you think?

**Comment by pemontto** [comment]
:+1:

**Comment by guyboertje** [comment]
We will not be adding this feature it can be done with multiple inputs.
