### ISSUE TITLE
logstash-input-redis:can we encrypt "password" which in the config file

### ISSUE THREAD

**Issue by w00308045** [logstash-plugins/logstash-input-redis#47]
logstash-input-redis:can we encrypt "password" which in the config file

**Comment by karthikr77** [comment]
Enhanced to read password from keystore or read from any custom valut store or azure key vault etc.

**Comment by jordansissel** [comment]
Logstash 6.2.0 has a [secret store feature](https://www.elastic.co/guide/en/logstash/current/keystore.html) you can use for this purpose.

**Comment by w00308045** [comment]
OK，Good Thank you


来自iPhone 邮差 ------------------原始邮件 ------------------发件人：Jordan Sissel <notifications@github.com>日期：2018-02-08 06:50:16收件人：logstash-plugins/logstash-input-redis <logstash-input-redis@noreply.github.com>抄送：w00308045 <youchai_w@aliyun.com>, Author <author@noreply.github.com>主题：Re: [logstash-plugins/logstash-input-redis] logstash-input-redis:can we encrypt "password" which in the config file (#47)Logstash 6.2.0 has a secret store feature you can use for this purpose.
