### ISSUE TITLE
Reliable queue delivery: Redis, Kafka, ... ?

### ISSUE THREAD

**Issue by mostolog** [logstash-plugins/logstash-input-redis#51]
Hi

In our ELK deployment we're looking for a 0.00% event loss.
Actually we are running a rsyslog using RELP to send logs to a Redis queue/list, readed from Logstash which inserts into Elasticsearch.

Are there any plans to implement Redis [RPOPLPUSH](http://redis.io/commands/rpoplpush) & [LREM](http://redis.io/commands/lrem) for **reliable queue delivery**?

Are the efforts regarding reliability placed on **kafka plugin** (as a reliable platform) instead?

As seems elastic was (**is?**) working for a reliable delivery https://github.com/elastic/logstash/issues/3693, should we consider other approach?

Regards

**Comment by jordansissel** [comment]
Can you narrow the focus of this issue to just redis since it is filed in
the redis input plugin?

**Comment by mostolog** [comment]
I was dealing with Redis, RPOPLPUSH & LREM are Redis commands, so I supposed this was the best place.

As you suggest, reliability isn't a Redis issue only, so probably I should reference this at https://github.com/elastic/logstash/issues/5636 and https://github.com/elastic/logstash/issues/5283

Anyway, this request it's to implement those commands, which will provide REDIS to LOGSTASH reliability. For the sake of truth, LREM could be a https://github.com/logstash-plugins/logstash-output-redis.
