### ISSUE TITLE
Documentation on default codec is wrong. It lists "plain" but is using "json".

### ISSUE THREAD

**Issue by jakommo** [logstash-plugins/logstash-input-redis#57]
Documentation lists `plain` as [default codec](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html#plugins-inputs-redis-codec), but it's [actually using](https://github.com/logstash-plugins/logstash-input-redis/blob/master/lib/logstash/inputs/redis.rb#L24) `json`. 
Same on the output https://github.com/logstash-plugins/logstash-output-redis/issues/47

**Comment by dedemorton** [comment]
This issue is resolved with https://github.com/elastic/logstash/pull/9139
