### ISSUE TITLE
All threads are taking the same message at the same time

### ISSUE THREAD

**Issue by PORN-FLAKES** [logstash-plugins/logstash-input-redis#60]
Hello, I have Logstash 5.6.1 running with Redis input plugin. Config:

    redis {
        codec => elog {
            elog_definitions => "elog-structure.yml"
        }
        data_type => "channel"
        key => "tst_key"
        batch_count => 125
        host => "XXXXXXXXXXX"
        port => 6379
        threads => 12
    }

We are running our own Java application to publish messages to Redis. Now the problem is with the threads. When you publish one message on Redis all 12 threads take the same message at the same time (checked using tcpdump that 12 exactly same packets arrive to logstash basically at the same time and checked the publish count using redis-cli monitor and tcpdump, oh and with 1 thread in config everything looks fine). Or maybe it is intended to work like this and we should be using something like RPOP and list data_type? I am not an expert on Redis...

**Comment by jordansissel** [comment]
Channels in Redis will broadcast one message to all subscribers. There is no way to change this behavior, to my knowledge.

If you want to have a one-message-to-one-subscriber model, you will need to use the 'list' data type.

**Comment by PORN-FLAKES** [comment]
Thanks for the lightning fast response. I suspected that it might work that way. Will try to check that list data type.
