### ISSUE TITLE
remove redis input list_listener custom LUA

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-redis#8]
(This issue was originally filed by @colinsurprenant at https://github.com/elastic/logstash/issues/1780)

---

the custom LUA script used for batching items from list could be replaced with :

```ruby
redis.pipelined do
  redis.multi do
    redis.lrange(...)
    redis.ltrim(...)
  end
end
```

so basically, doing a lrange fetches a batch of items without deleting them, ltrim deletes them, wrapped in a multi to make this atomic and wrapped in a pipeline to avoid multiple network roundtrips.

**Comment by guyboertje** [comment]
we might be opening ourselves to a world of redis ruby client bug pain with an untried (for us) execution path.

I suggest we improve the LUA script to do the same.
From:
```lua
    redis_script = <<EOF
          local i = tonumber(ARGV[1])
          local res = {}
          local length = redis.call('llen',KEYS[1])
          if length < i then i = length end
          while (i > 0) do
            local item = redis.call("lpop", KEYS[1])
            if (not item) then
              break
            end
            table.insert(res, item)
            i = i-1
          end
          return res
EOF
```

To:
```lua
    redis_script = <<EOF
          local batchsize = tonumber(ARGV[1]) - 1
          local result = redis.call('lrange', KEYS[1], 0, batchsize)
          redis.call('ltrim', KEYS[1], batchsize)
          return result
EOF
```
As the LUA script is executed atomically, the lrange and ltrim will get and remove the same items.

**Comment by guyboertje** [comment]
I think my arguments for keeping the LUA script are valid (comments from this PR) [1](https://github.com/logstash-plugins/logstash-input-redis/pull/36#discussion_r55253418), [2](https://github.com/logstash-plugins/logstash-input-redis/pull/36#discussion_r55276740)

> My take on this:
- I don't think the script is a bad thing as such - unless a customer does not want us to put a LUA script on their server.
- The [script is a transaction](http://redis.io/topics/transactions#redis-scripting-and-transactions) and transactions may be removed.
- By using pipeline and multi in the ruby driver, we open ourselves up to a new code execution path that we have not debugged yet.  Maybe the ruby driver does it well but we don't need the agro.
- The evalsha method, wrt ruby/jruby, is lightweight.
- The actual cost of the various batching mechanisms will not be seen on any realistic LS filter config.

Closing...

**Comment by jordansissel** [comment]
+1 to keeping LUA based on your arguments.
