### ISSUE TITLE
commands_map broken after switch to redis ~4

### ISSUE THREAD

**Issue by kzemek** [logstash-plugins/logstash-input-redis#80]
redis-rb 4 [introduced  a breaking change in version 4.0](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#40) where `redis.client` became a `CLIENT` command to Redis server. This breaks commands_map that [sets values on `redis.client.command_map`](https://github.com/logstash-plugins/logstash-input-redis/blob/master/lib/logstash/inputs/redis.rb#L160), but probably also the whole [`subscribe_stop` function](https://github.com/logstash-plugins/logstash-input-redis/blob/master/lib/logstash/inputs/redis.rb#L268).

An easy fix is to just replace `redis.client` with `redis._client`, as I've done here: https://github.com/path-network/logstash-input-redis/commit/fb7e374e1a2e0ed2310fe76e9ae6a3daf6c1dbc3

According to the [redis-rb changelog for 4.0.1](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#401) the proper way to replace `client` usage is to use a new `redis.connection` function instead.

**Comment by kares** [comment]
Thanks for the report, we pushed 3.6.1 please let us know if you run into any issues.
In the fix we tried to avoid using the 'internal' `_client` unless necessary: https://github.com/logstash-plugins/logstash-input-redis/pull/86 ... but otherwise it started based on your suggestions.
